### PR TITLE
feature: add onlyGetOpenGraphInfo image option

### LINKED ISSUE #238: Opengraph image shows a pdf icon in this case
**Describe the bug**
The open-graph-scraper falls back to returning the first image in the page as the opengraph image. Sometimes this could be undesirable as the first image in the page could be a random icon like a pdf icon.

**To Reproduce**
1. Use opengraph scraper to request data for https://lernplattform.involas.com/course/view.php?id=13&section=1
2. Notice that as ogImage a image of a pdf is returned

**Expected behavior**
When no ogImage is available, no image is returned.

**Actual behavior**
When no ogImage is available, the first image in the page is returned. Sometimes this could be misleading, as the first image could just be a random icon like a pdf icon. 

**Screenshots**
ogs-data

**Additional context**

open-graph-scraper provides an option `onlyGetOpenGraphInfo: true` that where it will not fallback to the first image it finds in the html. It does indeed solve the image problem, but returns much less data for title and description. 

Perhaps it might be a good idea to add an option like `onlyGetOpenGraphInfo: "image"`, so that lots of data is returned for title and description and still the image would always be accurate (e.g. not a random icon sometimes like a pdf icon)

**Additional Information**

On https://www.opengraph.xyz, no ogImage is displayed for https://lernplattform.involas.com/course/view.php?id=13&section=1. 

og-image-90

 - OS: Linux
 - Node Version:22

 - openGraphScraper Version: 6.7.0

### PR DESCRIPTION
**Pull request by SimonSiefke**
fixes #238 

With onlyGetOpenGraphInfo: image, lots of data is returned for title and description and the image would always be accurate (e.g. not a random icon which currently could happen in some edge cases).

### CODE REVIEW

**Comment by jshemas** [comment]
Hello. Thanks for the PR! Should `options.onlyGetOpenGraphInfo` be a `boolean` or a `array` of fall backs to not use?

**Comment by SimonSiefke** [comment]
Thanks for the feedback! I changed the code to use an array or boolean.

**Comment by jshemas** [comment]
@SimonSiefke This looks good! Can you fix the eslint errors and update the readme?

**Comment by jshemas** [comment]
Thanks for the PR! The tests are failing for a unrelated reason.

**Comment by jshemas** [comment]
changes are live in `open-graph-scraper@6.8.0`

**Pull request merged**
