### PR TITLE
Catch iconv exception to prevent unexpected charset

### PR DESCRIPTION
**Pull request by mattohoh**

### CODE REVIEW

**Comment by jshemas** [comment]
Thanks for the PR! Do you have a example of a site that this might happen on?

**Comment by mattohoh** [comment]
Check `http://www.tnnbar.org.tw/`

**Comment by jshemas** [comment]
thanks for the example! This pr looks great!

**Comment by jshemas** [comment]
changes can be found in `open-graph-scraper@3.1.3`

**Pull request merged**
