### PR TITLE
Promisify module

### PR DESCRIPTION
**Pull request by gazay**
After that you can do following things:
```js
    ogs(options).then(results => {
      // work with results
      response.end(JSON.stringify(data));
    }).catch(err2 => {
      // report error
      response.statusCode = 400;
      response.end(`Not found ${requestUrl.query.url}`);
    });
```

### CODE REVIEW

**Comment by gazay** [comment]
node 0.10 don't have Promises, so I've updated travis config. If you want - I can provide polyfill for node 0.10

**Comment by jshemas** [comment]
Hello,

Thanks for the PR! Supporting node 0.10 isn't super important to me. But it looks like even after using node 6, all the CI tests fail. Can you look into this?

**Comment by gazay** [comment]
@jshemas i've fixed almost all specs except Twitch – video you've used there already deleted or something.

**Comment by jshemas** [comment]
Awesome! Thank!

**Pull request merged**
