### PR TITLE
fix: pick first title when there are multiple title tags.

### LINKED ISSUE #118: Strange fallback behavior with multiple title tags.
Hi. I've found multiple title tags are automatically concatenated and generate long ogTitle. I don't think this is the expected behavior. 

**example1**
Html below generates ogTitle: `foobarbaz`
```
<html><head><title>foo</title></head><body><svg><title>bar</title></svg><svg><title>baz</title></svg></body></html>
```

**example2**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
This page has many title tags inside svg tags. Fetching the page causes ogTitle to be 

`Date.prototype.toLocaleString() - JavaScript | MDNThis deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This API has not been standardized.This is an obsolete API and is no longer guaranteed to work.
`

You can check reproduction here.
https://codesandbox.io/s/quirky-wood-1z2t9?file=/package.json

This PR fixes the issue.
https://github.com/jshemas/openGraphScraper/pull/119

### PR DESCRIPTION
**Pull request by catnose99**
close #118

### CODE REVIEW

**Comment by jshemas** [comment]
Oh, great catch!

**Comment by jshemas** [comment]
Fix is in open-graph-scraper@4.8.1

**Comment by catnose99** [comment]
Thanks so much for quick response!

**Comment by jshemas** [comment]
Welcome!

**Pull request merged**
