### PR TITLE
Allow ogVideo to be either from og:video or og:video:url

### PR DESCRIPTION
**Pull request by nsillik**
Looks like I jumped the gun on that last PR. It looks like both `og:video` and `og:video:url` are valid tags for the URL of the video, this PR should handle both cases.

### CODE REVIEW

**Comment by jshemas** [comment]
Ha. Do you have example of a site using just `og:video` ?

**Comment by nsillik** [comment]
From: https://developers.facebook.com/docs/sharing/webmasters

image

**Comment by jshemas** [comment]
Right... I was hoping to have another example of someone using `og:video` so we could test for that.

**Comment by nsillik** [comment]
@jshemas added a test for a twitch.tv video, which uses just the `og:video` tag.

**Comment by jshemas** [comment]
Perfect! Thanks!

**Pull request merged**
