### PR TITLE
compile to ES5 for publishing to npm

### PR DESCRIPTION
**Pull request by torquemad**
I am using this library in a react project that uses Webpack. Unfortunately I have issues minifying my node_modules assets due to this package not being compiled to ES5 before it was published to npm. 

By using babel, this PR allows this package to be used on projects that need to support older browsers.

### CODE REVIEW

**Comment by jshemas** [comment]
Thanks for opening the PR!

I'm a little confused on what you are trying to do. Is the issue with the usage of `const`? What browsers are you trying to support? 

Why did you copy everything from the `lib` folder into a new `src` folder?

Why did you move everything around in `fields.js`? Are you using a different eslint rule set then the one in this project? This makes reviewing this PR harder...

**Comment by torquemad** [comment]
@jshemas Howdy, you'll have to pardon my ignorance, but I haven't published my own npm package before so i'm not 100% sure on project structure / conventions. I'm also using this library in the context of a statistically generated React application (not a nodejs environment, which this package might be intended for). The problem I'm having is Webpack (4) is unable to bundle my node_module assets correctly because this package is written in ES6. 

My understanding is it's common practice to compile to this standard before publishing your package to NPM. (see https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

- the issue is not with the usage of `const` specifically, but making the entire content of `/lib`  ES5 compatible
- lib has been copied into src (which is still ES2015). You would make any updates in `/src` and run Babel before publishing updates.
- anything that has been moved around in /lib files (which is making the PR huge) has happened because of Babel (no eslint config changes have been made)

Just shout out if you have any other questions

**Comment by jshemas** [comment]
I'm not sure if this PR fixes the problem. When installing your branch in a react project, I get this error:
```
Failed to minify the code from this file:

        ./node_modules/charset/index.js:24
```
`charset` is a dependency of this project and it looks like it uses `const`s. I'm not really sure what to do about that.

**Comment by torquemad** [comment]
It actually looks like you're having the same problem that I'm having with your library; one of your dependencies hasn't been published to NPM  in ES5. The two options I'm aware of are:
a) Fix the problem yourself and open a PR to charset
b) copy the library (from node_modules) into your source code and reference that, so it is also compiled to ES5.

What do you think would be the best approach?

**Comment by jshemas** [comment]
Since `charset` is a super small lib and it doesn't change much. I think it might be best to just pull it into the project.

So I started digging into this problem myself and pushed up a branch called `es5`. I used a eslint es5 rule set and updated my code to work with that. Unfortunately I still get compile errors.

Line with errors -> https://github.com/jshemas/openGraphScraper/blob/es5/lib/openGraphScraper.js#L88

My only guess is it might not like how i'm using a `Promise`, but i'll have to dig into it more.

**Comment by jshemas** [comment]
Hello. I ended up just refactoring my code to es5 and I think that will solve all of the issues with older browsers. Thanks for opening this PR anyways.

**Pull request closed without merging**
