### PR TITLE
Fix jsdoc param name

### PR DESCRIPTION
**Pull request by cm-dyoshikawa**
Fix `validatorSettings` to `urlValidatorSettings`.

### CODE REVIEW

**Comment by jshemas** [comment]
Good catch! Can you run `npm run build` and commit the new `dist` changes?

**Comment by cm-dyoshikawa** [comment]
@jshemas Thank you for checking. I do it 😄

**Comment by jshemas** [comment]
Thank for the fix! Will publish with the next changeset

**Comment by cm-dyoshikawa** [comment]
Thank you for merging!

**Comment by jshemas** [comment]
changes are live in `open-graph-scraper@6.5.0`

**Pull request merged**
