### PR TITLE
fix: check if script text is non null before parsing

### PR DESCRIPTION
**Pull request by manan19**

### CODE REVIEW

**Comment by jshemas** [comment]
Thanks for the PR! Do you have any examples of real world websites where this happens?On Jun 27, 2024, at 1:30 PM, Manan ***@***.***> wrote:﻿



You can view, comment on, or merge this pull request online at:
  https://github.com/jshemas/openGraphScraper/pull/230

Commit Summary

  f844814  fix: check if script text is non null before parsing


File Changes  (1 file)

  
    M
    lib/extract.ts
    (6)
  


Patch Links:

  https://github.com/jshemas/openGraphScraper/pull/230.patch
  https://github.com/jshemas/openGraphScraper/pull/230.diff

**Comment by jshemas** [comment]
Can you also fix the eslint errors? `npm run eslint`

**Comment by manan19** [comment]
> Thanks for the PR! Do you have any examples of real world websites where this happens?

https://objkt.com/landing/objkt-paint?utm_source=warpcast&utm_medium=organic&utm_campaign=objktpaint98

**Comment by jshemas** [comment]
Thanks for the PR!

**Pull request merged**
